### ISSUE TITLE
Improve the method process reading CSV File by making it shorter

### ISSUE THREAD

**Issue by jomariabejo** [jomariabejo/MO-IT103-Group-Abejo#2]
To be enhance method [Link](https://github.com/jomariabejo/MO-IT103-Group-Abejo/blob/826338d10d5a191933320c78c10e1b7b4848e48e/src/main/java/com/payrollsystem/jomariabejo/utils/CsvUtils.java#L14)
- [x] Breakdown into Smaller Functions
- [ ] Error Handling
### TODO: 12/23/2023
- [ ] Replace double spaces with single spaces in Birthday field.
- [ ] Reintroduce commas in the address data.
- [ ] Add commas to monetary values for consistency.

**Comment by jomariabejo** [comment]
#1 Read EmployeeCSV
We will get this data if we use comma as dilimeter for employee CSV
Example:
10002,
Mata,
Christian,
"October 21,
 1987",
"90 O'Keefe Spur Apt. 379,
 Catigbian 2772 Sulu ",
783-776-744,
49-2959312-6,
824187961962,
103-100-522-000,
631052853464,
Regular,
Account Team Leader,
"Romualdez,
 Fredrick",
"42,975",
"1,
500",
800,
800,
"21,
488",
255.80

**Comment by jomariabejo** [comment]
# Eliminate the whitespace at the beginning and end of String.

```10001,
Crisostomo,
Jose,
"February 14,
1988",
"17/85 Stracke Via Suite 042,
Poblacion,
Las Piñas 4783 Dinagat Islands ",
918-621-603,
49-1632020-8,
382189453145,
317-674-022-000,
441093369646,
Regular,
HR Manager,
N/A,
"62,
670",
"1,
500",
"1,
000",
"1,
000",
"31,
335",
373.04
```

**Comment by jomariabejo** [comment]
### Concatenate the string starting from the first opening double quote, continuing until it reaches the closing double quote located at the last index of the array.

This is how it should seem.
```
10001
Crisostomo,
Jose,
"February 14,1988",
"17/85 Stracke Via Suite 042,Poblacion,Las Piñas 4783 Dinagat Islands ",
918-621-603,
49-1632020-8,
382189453145,
317-674-022-000,
441093369646,
Regular,
HR Manager,
N/A,
"62,670",
"1,500",
"1,000",
"1,000",
"31,335",
373.04
```

**Comment by jomariabejo** [comment]
![image](https://github.com/jomariabejo/MO-IT103-Group-Abejo/assets/70135786/73754e9b-56bf-4889-b5ac-ef26893f0e36)

**Comment by jomariabejo** [comment]
```
public static void addAllEmployee() throws IOException {

        BufferedReader reader = new BufferedReader(new FileReader(CSVFileNames.EMPLOYEE_DETAILS_CSV));

        reader.readLine(); // This will read the first line and skip it.

        String line;

        while ((line = reader.readLine()) != null) {

            ArrayList<String> employeeProcessedData = new ArrayList();

            // Split the line into an array using comma as delimiter
            String[] rowData = line.split(",");

            // Declare a boolean as flag that our concatenator is open
            boolean concatOpen = false;
            /**
             * Declare a string builder for modifying string content.
             * Think of it like a dark room and we have a small bag(string) and large bag(string builder).
             * Then we start to get things, we put small things(unmodified string) to small bag,
             * meanwhile we put large things inside the larger bag(modified string).
             *
             * We use flag(concatOpen)to determine whether the string needs to be modified.
             * We continue to modify large things(modified string) until we're satisfied.
             */
            StringBuilder stringBuilder = new StringBuilder();

            for (int currentColumn = 0; currentColumn < rowData.length; currentColumn++) {
                String string = rowData[currentColumn];
                if (concatOpen) {
                    /**
                     * Verify whether the string has double quotes (") at the end of it.
                     * if it does, we will turn off the concatOpen
                     */
                    if (iBooleanUtils.isTrailingCharDoubleQuote(string)) {
                        concatOpen = false;

                        /**
                         * ⚠️ Since the comma serves as our delimiter to cut the row line into multiple strings,
                         * we'll include it once more to validate our birthday string.
                         *
                         *
                         * ✅ Check if the string contains a month.
                         * if it does, we will add a comma, otherwise, the string won't be changed.
                         */

                        boolean strHasMonth = MonthChecker.isStringContainsMonth(stringBuilder.toString());

                        if (strHasMonth) {
                            String year = string;
                            stringBuilder.append(", " + year);
                        } else {
                            stringBuilder.append(string);
                        }

                        employeeProcessedData.add(stringBuilder.toString());
                        // Reset the StringBuilder for reuse.
                        stringBuilder.setLength(0);
                    } else {
                        stringBuilder.append(string);
                    }
                } else {
                    if (iBooleanUtils.isFirstCharDoubleQuote(string) || iBooleanUtils.isFirstCharWhitespace(string)) {
                        stringBuilder.append(string);
                        concatOpen = true;
                    } else {
                        concatOpen = false;
                        employeeProcessedData.add(string);
                    }
                }
            }
        }
    }
```

**Comment by jomariabejo** [comment]
### Inconsistent Double Space in Birthday Data
```
There is an inconsistency observed in the birthday data where double spaces are present. For example:
February 29,  1988

A new method is needed to ensure consistency in the formatting of birthday data.
```

**Comment by jomariabejo** [comment]
Youtube: [Debugging Journey: Fixing 'addAllEmployee' Method & Creating To-Do Tasks | Dec 23, 2023
](https://youtu.be/9z-qRwhyKNE?feature=shared)

### TODO: 12/23/2023
- [ ] Replace double spaces with single spaces in Birthday field.
- [ ] Reintroduce commas in the address data.
- [ ] Add commas to monetary values for consistency.

**Comment by jomariabejo** [comment]
Readding comma to address is so damn challenging 😵‍💫
![image](https://github.com/jomariabejo/MO-IT103-Group-Abejo/assets/70135786/29a42868-7ee8-4c72-afdf-04cdd081498d)
